# Generated by Django 4.2.7 on 2026-02-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
    ]
