# Generated by Django 4.2.7 on 2026-02-20 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='main_contactmessage',
        ),
    ]
