# Generated by Django 4.2.7 on 2026-02-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactmessage_admin_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_answered',
        ),
    ]
