# Generated by Django 4.2.7 on 2026-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_contactmessage_admin_reply_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='idx_cart_session',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='idx_cart_user',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
