# Generated by Django 4.2.7 on 2026-03-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_cartitem_idx_cart_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_answered',
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['session_key'], name='idx_cart_session'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user'], name='idx_cart_user'),
        ),
    ]
