# Generated by Django 4.2.7 on 2026-03-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_lesson_module_quiz_modulequiz_lesson_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulequiz',
            name='module',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ModuleQuiz',
        ),
    ]
