# Generated by Django 6.0.3 on 2026-03-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_enrollment_completion_date_enrollment_is_completed_and_more'),
        ('main', '0015_review_lessonprogress'),
    ]

    operations = [
    ]
